### PR TITLE
Digest authentication was improved

### PR DESCRIPTION
**Pull request by MrVine**
Using information from [here](https://en.wikipedia.org/wiki/Digest_access_authentication) digest authentication method was expanded to support more subtypes of this auth type.

### CODE REVIEW

**Comment by chuckwagoncomputing** [comment]
SabreDAV is throwing a 500 error with this. I'll look into it when I find some time.

**Comment by MrVine** [comment]
@chuckwagoncomputing , can you provide SabreDAV server's response, please?

**Comment by chuckwagoncomputing** [comment]
It's a 500. It appears that the body of the propfind request is not being sent. I tried my last change again and got the same result. Apparently something has changed on my end, but I'm not sure what. If this change is working for you I'd say we should go ahead and merge it and I'll try to find my problem from there.

**Comment by MrVine** [comment]
@chuckwagoncomputing , I create issue #20 to describe this problem. After I tried to find problem, found it, fix it and send this fix as pull-request #21. When you will have a time, please try to use the code from this pull-request to make request to SabreDav server, and write results here. Hope it fix this problem.

**Comment by MrVine** [comment]
@chuckwagoncomputing , any news?

**Comment by chuckwagoncomputing** [comment]
I can confirm that this is working with SabreDAV.

**Comment by chripo** [comment]
Awesome! Thank you very much.

**Pull request merged**
